/*Trigger class to handle operation 
trigger name - BulkCampaignTrigger on Campaign (after insert, after update, before insert, before update)*/

public with sharing class BulkCampaignTriggerHandler {
	/*====================================================================Program 1=================================================================*/
	/**/
	public static void closeOpportunityOnCampaign(List<Campaign> campList)
	{
		
	}
    
}