/**
 * @Created by ABHISHEK on 12-07-2019.
 * @Description Class to compile the org trigger's
 * @Created Date
 */

global without sharing class CompilerAllTriggerCustom {
    webservice static void allCompileTrigger() {
        /* List<String> listOfTrigger = new List<String>();
         List<ApexTrigger> triggersList = [SELECT Id,Name, NamespacePrefix from ApexTrigger LIMIT 10000];
         System.debug('===> Count is: ' + triggersList.size());
         for (ApexTrigger at : triggersList) {
             listOfTrigger.add(at.name);
             System.debug('===> Trigger name is: ' + at.name);
         }
         List<CompileTriggerResult> ctrList = apexBinding.compileTriggers(listOfTrigger);
         return compileTriggers(listOfTrigger);*/

}
}